const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const photos=[];
function gallery(items){return `<div class="gallery ${items.length===1?'one':''}">${items.map(p=>{const i=photos.push(p)-1;return `<button class="photo" data-photo="${i}" aria-label="Enlarge ${esc(p.caption)}"><img src="${esc(p.src)}" alt="${esc(p.caption)}" loading="lazy"><span>${esc(p.caption)} ↗</span></button>`}).join('')}</div>`}
function links(items){return `<div class="links">${items.map(([label,url])=>`<a href="${esc(url)}" target="_blank" rel="noreferrer">${esc(label)} ↗</a>`).join('')}</div>`}
document.querySelector('#stay-list').innerHTML=stays.map(s=>`<article class="stay" id="${s.id}" data-kind="${s.kind}"><div class="stay-head"><div><span class="eyebrow">${esc(s.town)} · ${s.kind==='rental'?'Airbnb':'Hotel / inn'}</span><h3>${esc(s.name)}</h3><span class="tag">${esc(s.tag)}</span><p class="intro">${esc(s.intro)}</p></div><div class="price ${s.live?'live':''}"><strong>${esc(s.price)}</strong><span>${esc(s.status)}</span><small>${esc(s.priceNote)}</small></div></div>${gallery(s.photos)}<div class="stay-info"><div class="facts"><div><h4>The stay</h4><p>${esc(s.room)}</p></div><div><h4>For working</h4><p>${esc(s.work)}</p></div><div><h4>With Rue</h4><p>${esc(s.rue)}</p></div></div><p class="catch">${esc(s.catch)}</p>${links(s.links)}<details><summary>Price, room and booking notes</summary><p>${esc(s.notes)}</p></details></div></article>`).join('');
document.querySelector('#town-list').innerHTML=towns.map(t=>`<article class="town">${gallery(t.photos)}<div><span class="eyebrow">${esc(t.drive)} from Providence</span><h3>${esc(t.name)}</h3><span class="tag ${t.pending?'pending':''}">${esc(t.label)}</span><p>${esc(t.pitch)}</p><p><strong>Our version:</strong> ${esc(t.plan)}</p><p><strong>With Rue:</strong> ${esc(t.baby)}</p><small>${esc(t.cost)}</small>${links(t.links)}<details><summary>Dates, prices and source notes</summary><p>${esc(t.notes)}</p></details></div></article>`).join('')+`<div class="town-extra"><span class="tag pending">Possible Thursday evening · date unconfirmed</span><h3>Chepachet candlelight shopping</h3><p>About 30–40 minutes from Providence. A smaller old-fashioned village outing with decorated shops and vintage streetlights. The organizer describes Thursday evenings in December, but its page still lists 2025. December 3 is a candidate, not a confirmed 2026 event. A short visit would be enough with Rue.</p><a href="https://www.candlelightshopping.com/" target="_blank" rel="noreferrer">Check the organizer’s updated calendar ↗</a></div>`;
const cards=[...document.querySelectorAll('.stay')];
function filter(kind){let count=0;cards.forEach(c=>{c.hidden=kind!=='all'&&c.dataset.kind!==kind;if(!c.hidden)count++});document.querySelector('#stay-count').textContent=`${count} stays · ${photos.length} enlargeable photos across the page`;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===kind)))}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>filter(b.dataset.filter)));
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>{if(cards.some(c=>'#'+c.id===a.getAttribute('href')))filter('all')}));filter('all');
const modal=document.querySelector('#lightbox');let current=0,trigger;
function show(i){current=(i+photos.length)%photos.length;const p=photos[current];document.querySelector('#full-photo').src=p.src;document.querySelector('#full-photo').alt=p.caption;document.querySelector('#caption').textContent=p.caption;document.querySelector('#photo-count').textContent=`${current+1} / ${photos.length}`;document.querySelector('#photo-source').href=p.source;}
document.querySelectorAll('[data-photo]').forEach(b=>b.addEventListener('click',()=>{trigger=b;show(Number(b.dataset.photo));modal.showModal()}));
document.querySelector('#close').addEventListener('click',()=>modal.close());document.querySelector('#previous').addEventListener('click',()=>show(current-1));document.querySelector('#next').addEventListener('click',()=>show(current+1));modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});modal.addEventListener('close',()=>trigger?.focus());modal.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();show(current+1)}if(e.key==='ArrowLeft'){e.preventDefault();show(current-1)}});

// Current six-night plan. Keep the older research below as price history, while
// making the exact Nov 26–Dec 2 Newport quotes the first lodging comparison.
document.title='Newport & Rhode Island · Nov 26–Dec 2';
document.querySelector('nav span').textContent='2026 · CURRENT PLAN: NOV 26–DEC 2';
document.querySelector('.lead').textContent='Newport for decorated mansions, a walkable harbor and six nights without changing stays.';
document.querySelector('.jump').innerHTML='<a href="#newport-six-night">New Newport prices ↓</a><a href="#stay-locations">Map the stays ↓</a><a href="#weather">Estimated weather ↓</a><a href="#towns">Christmas outings ↓</a>';
document.querySelector('.recommend').innerHTML='<strong>Current dates: Nov 26–Dec 2 · 6 nights</strong><p><strong>Stay in Newport.</strong> The Thames Street two-bedroom is the best family setup at $1,999.79 including tax. The downtown one-bedroom condo is $1,647.30 all-in; Hammetts is the strongest walkable hotel at $1,669 all-in.</p><a href="#newport-six-night">See the new shortlist →</a>';
const currentNewport=document.createElement('section');
currentNewport.id='newport-six-night';currentNewport.className='new-date-lead';
currentNewport.innerHTML=`<div class="section-head"><div><p class="eyebrow">Newport first · live quotes checked October 6</p><h2>Six nights, priced for your actual dates.</h2></div><p>November 26–December 2, 2026 · 2 adults + Rue as an infant. Airbnb totals include displayed taxes; hotel totals include taxes and fees. Nothing is held.</p></div>
<div class="date-pick"><div><span>MY PICK</span><h3>Thames Street Guesthouse</h3><strong>$1,999.79 all-in</strong><p>Two queen bedrooms, 1.5 baths, full kitchen, in-unit laundry, private deck and a Pack ’n Play. It is a real two-level apartment in the heart of Newport, rated 4.97. The catches are steep stairs and no off-street parking.</p><small>$1,755 discounted stay + $244.79 tax. Free cancellation before Nov 25 was displayed.</small><a href="https://www.airbnb.com/rooms/893465281226399076?adults=2&check_in=2026-11-26&check_out=2026-12-02&infants=1" target="_blank" rel="noopener">Open exact-date Airbnb ↗</a></div><img src="../../assets/providence-winter/newport-thames-0.avif" alt="Thames Street Guesthouse in Newport"></div>
<div class="six-night-grid">
<article class="six-stay"><img src="https://a0.muscache.com/im/pictures/miso/Hosting-604287529691477621/original/8abcdbb6-76b5-45fc-9c04-6139e72f2e9b.jpeg?im_w=720" alt="Downtown Newport condo near Thames Street" loading="lazy"><div><span>BEST LOWER-PRICE AIRBNB</span><h3>Downtown condo · steps to Thames</h3><strong>$1,647.30 all-in</strong><p>King bedroom plus queen sofa bed, kitchen and in-unit laundry. Public parking lot next door; the living-room sleeper makes naps and remote work overlap.</p><small>$1,445 stay + $202.30 tax · 4.93 / 152</small><a href="https://www.airbnb.com/rooms/604287529691477621?adults=2&check_in=2026-11-26&check_out=2026-12-02&infants=1" target="_blank" rel="noopener">Airbnb ↗</a></div></article>
<article class="six-stay"><img src="https://a0.muscache.com/im/pictures/miso/Hosting-837652093584221006/original/62e9f8d8-ad22-4609-a8d6-e4d11a22cb20.jpeg?im_w=720" alt="Newport penthouse with harbor view" loading="lazy"><div><span>BEST VIEW + WORK DESK</span><h3>Harbor-view penthouse</h3><strong>$1,442.33 all-in</strong><p>King bed, huge harbor-view deck, dedicated workspace, laundry and free parking. It is studio-style on the third floor with 30 steps, so there is no separate room for Rue.</p><small>$1,265.20 non-refundable stay + $177.13 tax · 4.93 / 229</small><a href="https://www.airbnb.com/rooms/837652093584221006?adults=2&check_in=2026-11-26&check_out=2026-12-02&infants=1" target="_blank" rel="noopener">Airbnb ↗</a></div></article>
<article class="six-stay"><img src="https://images.trvl-media.com/lodging/45000000/44370000/44364000/44363940/226d85c6.jpg?impolicy=fcrop&w=900&h=600" alt="Hammetts Hotel on the Newport waterfront" loading="lazy"><div><span>BEST WALKABLE HOTEL</span><h3>Hammetts Hotel</h3><strong>$1,669 all-in</strong><p>Wharfside, rated 9.2, and fully refundable at the displayed rate. Easy harbor walks and restaurants; a hotel room is less practical for calls and naps than the two-bedroom Airbnb.</p><small>Taxes and fees included · 7 rooms left at quote</small><a href="https://www.expedia.com/Newport-Hotels-Hammetts-Hotel.h44363940.Hotel-Information?chkin=2026-11-26&chkout=2026-12-02&rm1=a2%3Ac1" target="_blank" rel="noopener">Hotel quote ↗</a></div></article>
<article class="six-stay"><img src="https://images.trvl-media.com/lodging/45000000/44240000/44239500/44239435/06623cfb.jpg?impolicy=fcrop&w=900&h=600" alt="Wayfinder Newport hotel room" loading="lazy"><div><span>BEST HOTEL VALUE</span><h3>Wayfinder Newport</h3><strong>$1,077 all-in</strong><p>Stylish and fully refundable at the displayed rate. It is outside the most walkable harbor core, so expect to drive or rideshare for mansion and wharf evenings.</p><small>Taxes and fees included · 2 rooms left at quote</small><a href="https://www.expedia.com/Newport-Hotels-Wayfinder-Hotel.h44239435.Hotel-Information?chkin=2026-11-26&chkout=2026-12-02&rm1=a2%3Ac1" target="_blank" rel="noopener">Hotel quote ↗</a></div></article>
<article class="six-stay"><img src="https://images.trvl-media.com/lodging/1000000/330000/327200/327192/6a01ec97.jpg?impolicy=fcrop&w=614&h=346" alt="Atlantic Beach Hotel near Newport" loading="lazy"><div><span>POOL + LOWEST HOTEL</span><h3>Atlantic Beach Hotel</h3><strong>$755 all-in</strong><p>Indoor pool, cribs included and a fully refundable rate. It is in Newport East rather than downtown, trading atmosphere and walkability for the lowest practical hotel total.</p><small>Taxes and fees included · 8.4 / 1,575</small><a href="https://www.expedia.com/Newport-Hotels-Atlantic-Beach-Hotel-Newport.h327192.Hotel-Information?chkin=2026-11-26&chkout=2026-12-02&rm1=a2%3Ac1" target="_blank" rel="noopener">Hotel quote ↗</a></div></article>
<article class="six-stay"><img src="../../assets/providence-winter/coast-sails-0.avif" alt="Sails Up waterfront cottage in Portsmouth" loading="lazy"><div><span>COZY COTTAGE OUTSIDE NEWPORT</span><h3>Sails Up · Portsmouth</h3><strong>$1,849 before tax</strong><p>The closest match to the cottage vibe you liked: two bedrooms, water outside and a fireplace. It is a drive from Newport and final checkout tax still needs adding.</p><small>4.94 / 88 · six-night discounted search subtotal</small><a href="https://www.airbnb.com/rooms/627508397661321211?adults=2&check_in=2026-11-26&check_out=2026-12-02&infants=1" target="_blank" rel="noopener">Airbnb ↗</a></div></article>
</div><p class="quote-stamp">Live browser checks: Airbnb checkout totals and Expedia totals on Oct 6, 2026. Prices and availability can change. Travel insurance was not added.</p>`;
document.querySelector('main').prepend(currentNewport);
