const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const photos=[];
function gallery(items){return `<div class="gallery ${items.length===1?'one':''}">${items.map(p=>{const i=photos.push(p)-1;return `<button class="photo" data-photo="${i}" aria-label="Enlarge ${esc(p.caption)}"><img src="${esc(p.src)}" alt="${esc(p.caption)}" loading="lazy"><span>${esc(p.caption)} ↗</span></button>`}).join('')}</div>`}
function links(items){return `<div class="links">${items.map(([label,url])=>`<a href="${esc(url)}" target="_blank" rel="noreferrer">${esc(label)} ↗</a>`).join('')}</div>`}
document.querySelector('#stay-list').innerHTML=stays.map(s=>`<article class="stay" id="${s.id}" data-kind="${s.kind}"><div class="stay-head"><div><span class="eyebrow">${esc(s.town)} · ${s.kind==='rental'?'Airbnb':'Hotel / inn'}</span><h3>${esc(s.name)}</h3><span class="tag">${esc(s.tag)}</span><p class="intro">${esc(s.intro)}</p></div><div class="price ${s.live?'live':''}"><strong>${esc(s.price)}</strong><span>${esc(s.status)}</span><small>${esc(s.priceNote)}</small></div></div>${gallery(s.photos)}<div class="stay-info"><div class="facts"><div><h4>The stay</h4><p>${esc(s.room)}</p></div><div><h4>For working</h4><p>${esc(s.work)}</p></div><div><h4>With Rue</h4><p>${esc(s.rue)}</p></div></div><p class="catch">${esc(s.catch)}</p>${links(s.links)}<details><summary>Price, room and booking notes</summary><p>${esc(s.notes)}</p></details></div></article>`).join('');
document.querySelector('#town-list').innerHTML=towns.map(t=>`<article class="town">${gallery(t.photos)}<div><span class="eyebrow">${esc(t.drive)} from Providence</span><h3>${esc(t.name)}</h3><span class="tag ${t.pending?'pending':''}">${esc(t.label)}</span><p>${esc(t.pitch)}</p><p><strong>Our version:</strong> ${esc(t.plan)}</p><p><strong>With Rue:</strong> ${esc(t.baby)}</p><small>${esc(t.cost)}</small>${links(t.links)}<details><summary>Dates, prices and source notes</summary><p>${esc(t.notes)}</p></details></div></article>`).join('')+`<div class="town-extra"><span class="tag pending">Possible Thursday evening · date unconfirmed</span><h3>Chepachet candlelight shopping</h3><p>About 30–40 minutes from Providence. A smaller old-fashioned village outing with decorated shops and vintage streetlights. The organizer describes Thursday evenings in December, but its page still lists 2025. December 3 is a candidate, not a confirmed 2026 event. A short visit would be enough with Rue.</p><a href="https://www.candlelightshopping.com/" target="_blank" rel="noreferrer">Check the organizer’s updated calendar ↗</a></div>`;
const cards=[...document.querySelectorAll('.stay')];
function filter(kind){let count=0;cards.forEach(c=>{c.hidden=kind!=='all'&&c.dataset.kind!==kind;if(!c.hidden)count++});document.querySelector('#stay-count').textContent=`${count} stays · ${photos.length} enlargeable photos across the page`;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===kind)))}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>filter(b.dataset.filter)));
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>{if(cards.some(c=>'#'+c.id===a.getAttribute('href')))filter('all')}));filter('all');
const modal=document.querySelector('#lightbox');let current=0,trigger;
function show(i){current=(i+photos.length)%photos.length;const p=photos[current];document.querySelector('#full-photo').src=p.src;document.querySelector('#full-photo').alt=p.caption;document.querySelector('#caption').textContent=p.caption;document.querySelector('#photo-count').textContent=`${current+1} / ${photos.length}`;document.querySelector('#photo-source').href=p.source;}
document.querySelectorAll('[data-photo]').forEach(b=>b.addEventListener('click',()=>{trigger=b;show(Number(b.dataset.photo));modal.showModal()}));
document.querySelector('#close').addEventListener('click',()=>modal.close());document.querySelector('#previous').addEventListener('click',()=>show(current-1));document.querySelector('#next').addEventListener('click',()=>show(current+1));modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});modal.addEventListener('close',()=>trigger?.focus());modal.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();show(current+1)}if(e.key==='ArrowLeft'){e.preventDefault();show(current-1)}});
