/* Static GitHub Pages edition. No inbox links, account IDs or authentication. */
(() => {
  'use strict';
  const stays = austriaStays;
  const money = n => new Intl.NumberFormat('en-US', {style:'currency',currency:'USD'}).format(n);
  const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const change = s => s.initialNights === 2 && s.quote !== null ? { dollars:s.initial-s.quote, percent:(s.initial-s.quote)/s.initial*100 } : null;
  const delta = s => { const d=change(s); return d ? `<div class="${d.dollars>0?'lower':s.status==='offer'?'higher':'neutral'}"><strong>${money(Math.abs(d.dollars))} ${d.dollars>0?'less':'more'}</strong><small>${Math.abs(d.percent).toFixed(1)}% ${d.dollars>0?'lower':'higher'}${s.status!=='offer'?' · no extra deal':''}</small></div>` : '<span class="neutral">Not comparable</span>'; };
  const listing = s => `https://www.airbnb.com/rooms/${s.id}?check_in=2026-09-12&check_out=2026-09-14&adults=2&infants=1`;
  document.getElementById('price-rows').innerHTML = stays.map(s => `<tr class="${s.total===null?'unconfirmed':''}"><td><a href="#stay-${s.id}">#${s.number} ${esc(s.name)}</a><small>${esc(s.host)} · ${esc(s.statusLabel)}</small></td><td>${money(s.initial)}<small>${s.initialNights} nights${s.initialNights===3?' · Sep 12–15':''}</small></td><td>${s.quote===null?'No 2-night quote':money(s.quote)}<small>${s.status==='offer'?`Special Offer · €${s.euro.toLocaleString()}`:s.quote!==null?'Calendar rate, not new offer':'Not comparable'}</small></td><td>${delta(s)}</td><td><strong>${s.total===null?'—':money(s.total)}</strong>${s.total!==null?`<small>${s.taxes?'Includes '+money(s.taxes)+' taxes':'No separate taxes shown'}</small>`:''}</td><td>${s.total===null?'—':money(s.total/2)}</td></tr>`).join('');
  document.getElementById('map-legend').innerHTML=stays.map(s=>`<a href="#stay-${s.id}"><span class="number">${s.number}</span><span><strong>${esc(s.host)}</strong><small>${esc(s.place)}</small></span></a>`).join('');
  const filter=document.getElementById('filter'), sort=document.getElementById('sort'), cards=document.getElementById('cards');
  function renderCards() {
    const visible=stays.filter(s=>filter.value==='all'||(filter.value==='offers'?s.status==='offer':s.total!==null)).slice().sort((a,b)=>sort.value==='savings'?(change(b)?.dollars??-Infinity)-(change(a)?.dollars??-Infinity):(a.total??Infinity)-(b.total??Infinity));
    cards.innerHTML=visible.map(s=>`<article class="card" id="stay-${s.id}"><div class="collage">${s.photos.map((p,i)=>`<button data-stay="${s.id}" data-photo="${i}" aria-label="Enlarge ${esc(s.name)}: ${esc(p.label)}"><img src="${esc(p.src)}" alt="${esc(s.name)}: ${esc(p.label)}" loading="lazy" decoding="async"><span>${esc(p.label)}</span></button>`).join('')}</div><div class="card-body"><div class="card-top"><span class="eyebrow">#${s.number} · ${esc(s.place)}</span><span class="badge ${s.status}">${esc(s.statusLabel)}</span></div><h3>${esc(s.name)}</h3><p class="byline">Hosted by ${esc(s.host)} · ★ ${esc(s.rating)}</p><p class="features">${esc(s.features)}</p><div class="stats"><div><span>Initial capture</span><strong>${money(s.initial)}</strong><small>${s.initialNights} nights${s.initialNights===3?', not 2':''}</small></div><div><span>${s.status==='offer'?'Offer total':'Current 2 nights'}</span><strong>${s.total===null?'Unconfirmed':money(s.total)}</strong><small>${s.total===null?'No valid 2-night quote':money(s.total/2)+' / night'}</small></div><div><span>Price change*</span>${delta(s)}</div></div><div class="reply"><p class="eyebrow">Host response · summarized</p><p>${esc(s.reply)}</p></div><p class="note">${esc(s.note)}</p>${s.expires?`<p class="deadline">${s.status==='offer'?'Offer':'Invitation'} deadline shown: ${esc(s.expires)}. Availability is not reserved.</p>`:''}<div class="links"><a href="${listing(s)}" target="_blank" rel="noopener noreferrer">View Airbnb listing ↗</a><a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.place+', Austria')}" target="_blank" rel="noopener noreferrer">Explore area ↗</a></div></div></article>`).join('');
  }
  const renderWithNearby=()=>{renderCards();attachNearbyLinks();};
  filter.addEventListener('change',renderWithNearby);sort.addEventListener('change',renderWithNearby);renderWithNearby();
  // A map/table link also reveals a card hidden by the current filter.
  document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#stay-"]');if(a){filter.value='all';renderWithNearby();}});
  const dialog=document.getElementById('gallery');let selected=null;let selectedIndex=0;let opener=null;
  function showPhoto(){const p=selected.photos[selectedIndex];document.getElementById('gallery-title').textContent=selected.name;document.getElementById('gallery-caption').textContent=p.label;document.getElementById('gallery-image').src=p.src;document.getElementById('gallery-image').alt=p.label;document.getElementById('gallery-count').textContent=`${selectedIndex+1} of ${selected.photos.length}`;}
  cards.addEventListener('click',e=>{const b=e.target.closest('button[data-photo]');if(!b)return;opener=b;selected=stays.find(s=>s.id===b.dataset.stay);selectedIndex=Number(b.dataset.photo);showPhoto();dialog.showModal();});
  document.getElementById('nearby-content').addEventListener('click',e=>{const b=e.target.closest('button[data-activity]');if(!b)return;const area=austriaAreas.find(a=>a.id===b.dataset.area);opener=b;selected={name:area.name+' · nearby places',photos:area.activities.map(a=>({src:nearbyPhoto(a),label:a.name+(a.video?' · Ryan Shirley video frame':' · photo credit below the activity card')}))};selectedIndex=Number(b.dataset.activity);showPhoto();dialog.showModal();});
  function step(n){if(selected){selectedIndex=(selectedIndex+n+selected.photos.length)%selected.photos.length;showPhoto();}}
  document.getElementById('previous').addEventListener('click',()=>step(-1));document.getElementById('next').addEventListener('click',()=>step(1));document.getElementById('close-gallery').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>opener?.focus());dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();step(-1);}if(e.key==='ArrowRight'){e.preventDefault();step(1);}});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
  try {
    if(!window.L)throw new Error('Leaflet unavailable');
    const map=L.map('map',{scrollWheelZoom:false});
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',maxZoom:18}).addTo(map);
    stays.forEach(s=>{if(s.number===7)return;const group=s.number===3?[s,stays.find(p=>p.number===7)]:[s];const popup=group.map(p=>`<strong>#${p.number} ${esc(p.name)}</strong><br>${esc(p.host)} · ${p.total===null?'No confirmed 2-night stay':money(p.total)+' / 2 nights'}<br><a href="#stay-${p.id}">See photos and reply</a>`).join('<hr>')+`<p>${esc(s.mapLabel)}</p>`;
      const area=nearbyAreaFor(s);const enrichedPopup=`<img class="popup-photo" src="${nearbyPhoto(area.activities[0])}" alt="${esc(area.activities[0].name)}">${popup}<p><strong>Nearby:</strong> ${esc(area.activities.map(a=>a.name).join(' · '))}</p><a class="popup-nearby" href="#nearby-${area.id}">Explore nearby activities →</a>`;
      if(s.number===8)L.circle([s.lat,s.lon],{radius:6500,color:'#9a6b21',weight:1,dashArray:'5 6',fillOpacity:.07}).addTo(map).bindPopup(enrichedPopup,{maxWidth:290});
      const width=group.length>1?54:36;const icon=L.divIcon({className:'',html:`<div class="map-pin ${s.number===8?'uncertain':''}">${group.map(p=>p.number).join(' · ')}</div>`,iconSize:[width,36],iconAnchor:[width/2,18]});L.marker([s.lat,s.lon],{icon,title:group.map(p=>p.name).join(' / ')}).addTo(map).bindPopup(enrichedPopup,{maxWidth:290});
    });map.fitBounds(stays.map(s=>[s.lat,s.lon]),{padding:[40,40],maxZoom:9});
  }catch(error){document.getElementById('map-error').hidden=false;document.getElementById('map').style.display='none';}
})();
