/* Activity research: September 4, 2026. Travel ranges are planning estimates,
   not live routes from private Airbnb addresses. */
const austriaNearbyCredits = {
  'kolm-saigurn': ['Tigerente', 'CC BY 4.0', 'https://creativecommons.org/licenses/by/4.0/', 'https://commons.wikimedia.org/wiki/File:Kolm_Saigurn_Rauris_20260606a.jpg'],
  'hintersteiner-see': ['Carsten Steger', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0/', 'https://commons.wikimedia.org/wiki/File:Aerial_image_of_Hintersteiner_See_(view_from_the_south).jpg'],
  'astbergsee': ['Mateus2019', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0/', 'https://commons.wikimedia.org/wiki/File:AUT_—_Tirol_—_Bezirk_Kitzbühel_—_Gde._Going_am_Wilden_Kaiser_—_Marchstraße_53_(Astbergsee_mit_Wildem_Kaiser_und_Wasserspiegelung)_Mattes_2023-09-28.jpg'],
  'wildkogel': ['User:Mattes', 'CC BY 2.0 DE', 'https://creativecommons.org/licenses/by/2.0/de/deed.en', 'https://commons.wikimedia.org/wiki/File:AUT_—_Land_Salzburg_—_Bezirk_Zell_am_See_—_Gemeinde_Neukirchen_am_Großvenediger_—_Sonnberg_247_(Wildkogel_·_Rahmen_für_Ausblick)_Mattes_2022-07-03.jpg'],
  'hollersbachtal': ['Edelmauswaldgeist', 'CC0', 'https://creativecommons.org/publicdomain/zero/1.0/', 'https://commons.wikimedia.org/wiki/File:Hollersbachtal_1.jpg'],
  'schmittenhoehe': ['C.Stadler/Bwag', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0/', 'https://commons.wikimedia.org/wiki/File:Schmittenhöhe_-_Gipfel_(b).JPG']
};
const austriaAreas = [
  {
    id:'rauris', name:'Rauris', stays:[1], tagline:'A quieter valley, with big mountain days on tap.',
    summary:'Best for a cabin-and-nature stay: valley walks locally, Kolm Saigurn deeper in the valley, and the Grossglockner road as a larger excursion. Less concentrated in Ryan’s headline sights than St. Wolfgang.',
    immediate:'Rauris village, riverside paths and meadow walks are the local options. The cabin’s exact address is not verified, so village access on foot is not guaranteed.',
    plan:'September 12: village or a short valley walk after arrival. September 13: Hochalm in clear weather, or Kolm Saigurn for forest, streams and waterfalls. Keep Grossglockner as an alternative full day, not another stop to squeeze in.',
    seasonal:'Hochalm is scheduled to run on Saturday September 12 and Sunday September 13, but not Monday September 14. September service is Wednesday/Saturday/Sunday; there is a midday break. Gold panning ends September 6, so it is not an option for this stay.',
    seasonalLinks:[['2026 lift calendar','https://www.hochalmbahnen.at/en/summer/adventure-mountain-hochalm/operating-times'],['Gold-panning season','https://www.hochalmbahnen.at/en/summer/adventure-mountain-hochalm/gold-panning']],
    extraTitle:'Also nearby: Hochalm adventure mountain',
    extra:'A roughly 10-minute gondola ride leads to mountain views and the birds-of-prey station. Published shows run on lift operating days at 11:00 and 14:30 (about 40 minutes). The operator lists baby-carriage and back-carrier rental; confirm availability before relying on it. Allow half a day, with a short walk rather than a big summit route.',
    extraLink:'https://www.hochalmbahnen.at/de/sommer/erlebnisberg-hochalm/greifvogelwarte',
    activities:[
      {name:'Kolm Saigurn',photo:'kolm-saigurn',alt:'Stream and footbridge below the mountains at Kolm Saigurn',access:'About 30–40 min drive from Rauris; seasonal toll-road access',duration:'2–4 hours with a short walk',description:'A high valley amphitheatre with streams, old forest and steep mountains overhead. It gives you a much wilder setting than a village stroll without committing to a summit. The photo shows the stream-and-bridge landscape, not a guaranteed roadside viewpoint.',family:'Pick a short marked out-and-back. Forest roots, rocks and waterfall approaches favour a carrier; longer Rauriser Urwald routes are not a flat stroller promenade.',official:'https://www.raurisertal.at/de/raurisertal/die-rauriser-taeler',query:'Kolm Saigurn Rauris'},
      {name:'Grossglockner High Alpine Road',video:'grossglockner-road',seconds:643,access:'About 40–55 min to Ferleiten toll entrance, then mountain driving',duration:'A full scenic day · roughly 5–7 hours overall',description:'Ryan’s switchbacks-and-peaks sequence: stop at viewpoints, then continue toward Kaiser-Franz-Josefs-Höhe for the Grossglockner and Pasterze landscape. The drive to the toll gate is only the start of the excursion.',family:'Best for scenery without a long hike, but expect bends, altitude, cold wind and frequent breaks. Viewpoints are enough; glacier descents are a separate, strenuous decision.',official:'https://www.grossglockner.at/gg/en/index',query:'Ferleiten Grossglockner toll station'}
    ]
  },
  {
    id:'going', name:'Going am Wilden Kaiser', stays:[3,7], tagline:'Limestone peaks, reflection lakes and Tyrolean meadows.',
    summary:'A strong choice for beautiful local landscapes and a quieter walking rhythm. Hintersteiner See and Astbergsee are additions to the video list; Kufstein is the nearby Ryan overlap. Jessica’s #3 has a two-night quote; Stefanie’s #7 still requires three nights.',
    immediate:'Going’s village lanes, church square and surrounding meadow paths are the local starting point. Both pins mark the town, not the buildings: confirm the actual walk from each apartment.',
    plan:'September 12: Going village and a short meadow walk. September 13: Hintersteiner See, leaving time to pause by the water. Choose Astberg instead if you want a real uphill hike; use Kufstein as the culture alternative.',
    seasonal:'Do not treat Astbergsee as a drive-up lake or a flat 3 km loop: the official route climbs 465 m over 3 km one way from the valley station. Any chairlift shortcut needs a separate date, operation and infant-carriage check.',
    seasonalLinks:[['Official Astberg route','https://www.wilderkaiser.info/en/tours/from-going-up-to-the-astbergsee.html']],
    activities:[
      {name:'Hintersteiner See',photo:'hintersteiner-see',alt:'Aerial view of turquoise Hintersteiner See framed by forest and mountains',access:'About 20–30 min drive from Going',duration:'2–3 hours at a relaxed family pace',description:'Clear turquoise water below the Wilder Kaiser, forested shores and mountain reflections. The official full loop is 5.2 km with 130 m of ascent, listed at 1½ hours for ordinary walking; a shorter shore visit is a perfectly good version.',family:'The whole circuit is not assumed stroller-friendly. Use a carrier for the full walk, or choose a short accessible shore stretch after checking local conditions. The photo is aerial, not the view from the walking path.',official:'https://www.wilderkaiser.info/en/tours/hintersteiner-see-circular-walk.html',query:'Hintersteiner See Scheffau'},
      {name:'Astbergsee',photo:'astbergsee',alt:'Wilder Kaiser mountains reflected in Astbergsee',access:'Local trail start at Astbergbahn valley station',duration:'Allow 3–4+ hours for the uphill walk and return',description:'The tiny reflection lake produces the classic Wilder Kaiser postcard view: a near-perfect mountain skyline mirrored in still water. Its appeal is the panorama and a lingering break, not a long lakeside circuit.',family:'The official uphill approach is 3 km each way and 465 m ascent. With an infant this is a carrier hike, not an easy stroller outing. Do not count on lift access without checking.',official:'https://www.wilderkaiser.info/en/tours/from-going-up-to-the-astbergsee.html',query:'Astbergsee Going'},
      {name:'Kufstein',video:'kufstein',seconds:566,access:'About 30–40 min drive from Going',duration:'2–4 hours',description:'Ryan’s compact fortress town: a riverside stroll along the Inn, old-town lanes and the fortress above the roofs. A useful change of pace when the higher mountains are clouded in.',family:'Keep the river and old town as the easy core. Check fortress lift access separately; interior routes and historic surfaces can still involve steps.',official:'https://www.kufstein.com/en',query:'Kufstein old town'}
    ]
  },
  {
    id:'neukirchen', name:'Neukirchen am Großvenediger', stays:[4], tagline:'The most convenient of these bases for Krimml.',
    summary:'A good waterfall-and-mountain pairing: Ryan’s Krimml sequence is a short drive west, and Wildkogel rises directly above the resort. This is a nature base, not a lakeside village.',
    immediate:'Neukirchen village, valley-floor paths and the Wildkogelbahn valley station are the local options. The chalet’s town-level pin does not establish that you can walk to the lift.',
    plan:'September 12: short village or valley walk. September 13: choose a clear-weather Wildkogel half day or a more substantial Krimml walk. A brief lower-falls visit can fit on a travel day if your onward route works.',
    seasonal:'Wildkogelbahn’s published daily summer operation runs through September 13. From September 14 operation is weather-dependent. Plan the mountain day before checkout, and reconfirm the morning of travel. A Nationalpark SummerCard is not automatically included with every rental.',
    seasonalLinks:[['2026 lift dates and times','https://media.wildkogel-arena.at/en/summer-2026-favourite-spot.html']],
    extraTitle:'Another valley option: Habachtal',
    extra:'The emerald valley east of Neukirchen offers a streamside walk into the Hohe Tauern. With an infant, make it a short out-and-back from the valley entrance; the deeper valley and huts are a longer hiking day, not a quick stop. Check trail conditions and any local valley transport before choosing the full route.',
    extraLink:'https://www.wildkogel-arena.at/en/activities-experiences/hiking.html',
    activities:[
      {name:'Wildkogel mountain views',photo:'wildkogel',alt:'Summer photo-frame viewpoint at Wildkogel above Neukirchen and Bramberg',access:'Wildkogelbahn in Neukirchen · local lift excursion',duration:'Half a day',description:'A lift-assisted way to spend time above the valley, with broad Hohe Tauern views, mountain restaurants and walking options. The photo is a real viewpoint on Wildkogel. Choose a short signed walk around the mountain station rather than automatically taking a long circuit.',family:'A gondola helps with the ascent, but high paths are still exposed to weather. Slides and mountain carts are not infant activities. Ask the lift team which current paths suit a stroller.',official:'https://www.wildkogel-arena.at/en/activities-experiences/hiking.html',query:'Wildkogelbahn Neukirchen'},
      {name:'Krimml Waterfalls',video:'krimml',seconds:600,access:'About 20–30 min drive from Neukirchen',duration:'1–2 hours lower falls; 3–5 hours for a longer uphill visit',description:'The closest Airbnb area to Ryan’s 380 m waterfall system. For maximum impact with limited effort, start with the lower waterfall rather than assuming you must climb every tier. Higher viewing platforms reveal different angles but require sustained climbing.',family:'The lower falls are roughly 10–15 minutes on foot from the entrance/parking area. Allow much longer with stops. Spray makes paths slippery; bring a carrier and waterproof layer for an uphill outing.',official:'https://www.wasserfaelle-krimml.at/en/',query:'Krimml Waterfalls parking'}
    ]
  },
  {
    id:'hollersbach', name:'Hollersbach im Pinzgau', stays:[5], tagline:'Streamside walking first; a private-spa evening afterwards.',
    summary:'Lena’s penthouse makes most sense if the sauna and whirlpool matter after a nature day. Hollersbachtal is the immediately local landscape, with Krimml and mountain lifts within reach.',
    immediate:'The village, bathing-lake area and the entrance to Hollersbachtal are local options. Confirm the apartment address before treating the trailhead as walkable from the door.',
    plan:'September 12: village and a short streamside walk. September 13: Krimml, or a longer Hollersbachtal outing if you prefer a quieter day with less driving. Panoramabahn is the clear-weather alternative.',
    seasonal:'The complete official Hollersbach nature-trail outing is 12 km return, 250 m ascent and around 5 hours. The family-friendly version here is deliberately a shorter out-and-back, not the entire route.',
    seasonalLinks:[['National park trail description','https://hohetauern.at/de/besuchen/themenwege/natur-und-kulturschaetze-im-nationalpark-hohe-tauern/2215-bachlehrweg-hollersbach.html']],
    extraTitle:'Also local: Panoramabahn to the Resterhöhe area',
    extra:'The Hollersbach gondola offers a mountain-view alternative to the valley walk, reaching the Resterkogel area via Breitmoos. The published 2026 summer season is June 20–October 11, with operating hours 08:45–16:15. Check weather and the chosen walking route; lift access does not make every trail stroller-friendly.',
    extraLink:'https://www.kitzski.at/media/drucksorten/EN-Bergsommer-2026.pdf',
    activities:[
      {name:'Hollersbachtal stream walk',photo:'hollersbachtal',alt:'Hollersbachtal stream, green pastures and an alpine hut',access:'Local valley entrance near Gasthof Seestube',duration:'1–2 hours for a short out-and-back; 5 hours for full official route',description:'A quieter Hohe Tauern scene: rushing water, green pastures, valley walls and alpine huts farther in. Follow the stream for as long as the day feels good, then turn back. The meadow-and-hut photo shows the valley beyond the village, not the trailhead.',family:'A flexible turnaround makes this easier to tailor than a summit circuit. Surface and slope vary; use a carrier where the track becomes rough, and do not promise the full route with a stroller.',official:'https://hohetauern.at/de/besuchen/themenwege/natur-und-kulturschaetze-im-nationalpark-hohe-tauern/2215-bachlehrweg-hollersbach.html',query:'Gasthof Seestube Hollersbach'},
      {name:'Krimml Waterfalls',video:'krimml',seconds:600,access:'About 30–40 min drive from Hollersbach',duration:'Half a day for the lower falls and a relaxed visit',description:'The strongest direct Ryan-video outing from this base. Start at the bottom for the force, sound and spray; add uphill platforms only if you want a more physical walk. It pairs naturally with a quiet evening at the penthouse.',family:'Keep spare dry layers handy. The higher waterfall path is a hike, not just a series of roadside overlooks; a lower-falls visit is a complete option in its own right.',official:'https://www.wasserfaelle-krimml.at/en/',query:'Krimml Waterfalls parking'}
    ]
  },
  {
    id:'zell', name:'Zell am See–Kaprun', stays:[2,8], tagline:'The best mix of low-effort lake time and bigger scenery.',
    summary:'The waterfront listing is a strong match if you want scenery without driving for every outing. Wanna Rise is only located to the broad region, so its convenience cannot yet be judged. Ryan covers Zell itself and the Grossglockner road.',
    immediate:'For #2, the listing’s lake-access claim is the main draw: confirm the actual shore access, barriers and walking route with an infant. #8 could be elsewhere in the Zell–Kaprun region; do not assume it has the same lake access.',
    plan:'September 12: lakeshore time after arrival. September 13: Schmittenhöhe or a lake cruise, especially if an included Summer Card is confirmed. Choose Grossglockner instead for a full driving day; don’t attempt all three.',
    seasonal:'Both listings mention the Summer Card, but confirm eligibility and issuance with the host. Through September 15, it starts at 15:00 on arrival day and four premium attractions are only available from the second day: Schmitten summit lifts, upper Kitzsteinhorn lifts, MS Schmittenhöhe cruise and Kaprun reservoirs. The ordinary guest card is not the same thing.',
    seasonalLinks:[['Official Summer Card conditions','https://www.zellamsee-kaprun.com/de/erleben/sommerkarte']],
    extraTitle:'Shorter add-on: Sigmund Thun Gorge + Klammsee',
    extra:'Near Kaprun, wooden walkways squeeze through a narrow, rushing-water canyon. The operator lists 263 steps: strollers are not allowed in the gorge, and a body-hugging baby carrier is recommended. September opening is listed as 09:00–17:30, subject to weather. Allow around 1½–2½ hours if adding time by Klammsee; travel time depends heavily on which listing you choose.',
    extraLink:'https://www.klamm-kaprun.at/faq/',
    activities:[
      {name:'Zeller See shore + lake cruise',video:'zell-am-see',seconds:621,access:'#2: east-shore area · #8: exact locality still unknown',duration:'1–3 hours; easy to shorten',description:'Ryan’s lake-resort scene, at an everyday pace: water, mountain backdrops, a promenade and a boat outing if you want to see the lake from the middle. Do a short shore stretch rather than turning it into a full-lake walking project.',family:'A good low-effort option. Verify the closest pier, September sailing times and stroller boarding. East-shore lodging does not automatically mean you are beside Zell’s old-town promenade.',official:'https://www.zellamsee-kaprun.com/en',query:'Zell am See lake promenade'},
      {name:'Schmittenhöhe',photo:'schmittenhoehe',alt:'Schmittenhöhe summit with chapel, cable car station and paraglider',access:'From east shore, roughly 20–30 min drive to summit-lift base',duration:'Half a day',description:'The local mountain gives you a high viewpoint without a summit ascent on foot: the lake below, ridgelines in every direction and space for a short walk near the top. This is an added nearby idea, not a separate named stop in Ryan’s list.',family:'Confirm the lift route and current easy paths with staff. Bring warm layers and sun protection; infant comfort and suitability for altitude are individual considerations. Check the Summer Card arrival rule above.',official:'https://www.schmitten.at/en',query:'Schmittenhöhebahn valley station'},
      {name:'Grossglockner scenic drive',video:'grossglockner-road',seconds:643,access:'Roughly 25–40 min from Zell area to Ferleiten, then alpine road',duration:'Full day · approximately 5–7 hours overall',description:'The most dramatic driving option near these stays: the high road, Edelweißspitze and the glacier-view landscape beyond. It is a clear-weather choice; in low cloud the extra driving buys much less.',family:'Plan breaks and warm clothes. The road is tolled and seasonal, and conditions may change quickly. Stay with accessible overlooks if you want scenery rather than a long mountain hike.',official:'https://www.grossglockner.at/gg/en/index',query:'Ferleiten Grossglockner toll station'}
    ]
  },
  {
    id:'wolfgang', name:'St. Wolfgang', stays:[6], tagline:'The clearest match to the lake scenes in Ryan’s video.',
    summary:'The best fit here if the trip is mainly about Wolfgangsee, Schafberg and Salzkammergut scenery. It costs more than the other confirmed stays, but several headline experiences are local rather than separate long drives.',
    immediate:'St. Wolfgang village and waterfront are the local core; the Schafberg railway and boat piers are in town. The duplex’s exact location is unverified, so ask Susan for real walking times and any steep approach.',
    plan:'September 12: waterfront, village and an optional boat trip. September 13: Schafberg in clear weather. If lake-and-mountain walking matters more than the railway, choose Gosausee instead; Hallstatt is an alternative, not a compulsory extra.',
    seasonal:'The Schafberg railway is scheduled daily to the summit through November 1, 2026. Wolfgangsee boats move to their late-season timetable September 7–October 26. Reserve/check the descent as well as the ascent. The operator also flags low-water boarding difficulties at some piers; confirm stroller access.',
    seasonalLinks:[['Railway and boat operating information','https://www.5schaetze.at/en/Info_SchafbergBahn_and_WolfgangseeSchifffahrt.html'],['Boat timetable and notices','https://www.5schaetze.at/de/wolfgangseeschifffahrt/preise-und-fahrplan.html']],
    activities:[
      {name:'Wolfgangsee + lakeside villages',video:'wolfgangsee',seconds:281,access:'Local lake and village; precise walk from duplex to be confirmed',duration:'1–4 hours, depending on boat route and stops',description:'A very good arrival-day outing without sacrificing the day: walk the waterfront, take in the mountain setting, then optionally sail to another village. Choose one stop rather than trying to collect the entire lake.',family:'The shore and village version is flexible and easy to shorten. Boats add logistics: check the last return and current pier accessibility, especially with a stroller.',official:'https://www.5schaetze.at/en/wolfgangseeschifffahrt.html',query:'St Wolfgang Schifffahrt'},
      {name:'Schafberg cog railway',video:'schafberg',seconds:300,access:'Local station in St. Wolfgang',duration:'3–4 hours including railway and summit time',description:'One of Ryan’s signature Austrian panoramas: climb above the lake by cog railway for a patchwork of blue water, ridges and villages. Pick the clearest part of the stay rather than fixing it to a cloudy afternoon.',family:'Keep a child securely held or carried near the summit: there are steep drops and exposed paths. This is not an unrestricted stroller playground. Book both the uphill and return journey.',official:'https://www.5schaetze.at/en/schafbergbahn.html',query:'Schafbergbahn St Wolfgang'},
      {name:'Vorderer Gosausee',video:'gosausee',seconds:107,access:'About 50–65 min drive from St. Wolfgang',duration:'Half a day including the drive',description:'A different kind of lake day: the Dachstein massif at the far end of the water, reflections and a shoreline walk. Stay with the front lake for an unhurried outing; the rear lakes add considerably more walking.',family:'Choose how far to walk after seeing conditions. The front-lake route is the gentler choice, but do not assume every side trail or extension is stroller-accessible.',official:'https://dachstein.salzkammergut.at/en/',query:'Vorderer Gosausee parking'},
      {name:'Hallstatt waterfront',video:'hallstatt',seconds:26,access:'About 45–60 min drive from St. Wolfgang',duration:'Half a day including parking and walking',description:'The famous village-and-lake view from the video, best treated as a focused waterfront outing. Arrive early for a quieter experience, walk the village and leave time by the water rather than building a checklist of paid attractions.',family:'Parking is outside the historic core; expect walking, crowds and some uneven surfaces. This recommendation is for the village only—not an assumption that the salt mine, Skywalk or other attractions are operating.',official:'https://www.hallstatt.net/',query:'Hallstatt visitor parking'}
    ]
  }
];
