const A = "../../assets/montana-ranch-trip/";

const stays = [
  {id:"clydesdale",name:"Clydesdale Outpost",place:"Whitefish · Glacier gateway",coords:[48.443,-114.363],price:"$$$",structure:"Flexible cabin nights",meals:"Full kitchen; meals on your own",baby:"Children welcome; no infant care",horses:"Working Clydesdale ranch",luxury:"Design-forward cabins",fit:"good",fitText:"Strong",tags:["flexible"],badges:["2-bedroom cabin","Working horse ranch","Glacier base"],summary:"The most literal farm-stay translation: six handsome two-bedroom cabins on a small working horse ranch, ten minutes from Whitefish. It gives you animals and independence without forcing a ranch schedule.",caution:"Clydesdale horseback rides start at 12 and the immersive Encounter at 7. With a one-year-old, choose the private carriage, barn time and pasture atmosphere—not the riding program.",facts:[["Stay style","Cabin + kitchen"],["Scale","6 cabins"],["Baby price","Check live rate"]],images:["clydesdale-hero.jpg","clydesdale-cabin.jpg"],url:"https://www.clydesdaleoutpost.com/",details:"https://www.clydesdaleoutpost.com/cabins"},
  {id:"flathead",name:"Flathead Lake Lodge",place:"Bigfork · Flathead Lake",coords:[48.048557,-114.077134],price:"$$$$",structure:"Sunday–Sunday, 7 nights",meals:"All meals, snacks + drinks",baby:"Age 2 and under free",horses:"Trail rides + elk preserve",luxury:"Classic, not polished-modern",fit:"caution",fitText:"Call now",tags:["inclusive","splurge"],badges:["All-inclusive","Lake + horses","Airport transfer"],summary:"The closest Montana equivalent to a fully bundled Austrian family resort—except the aesthetic is nostalgic summer camp. Horses, sailing, meals, drinks and family programming are wrapped into one week.",caution:"2026: $5,614 per adult in a lodge room ($11,228 for two) or $6,916 per adult in a cabin/suite ($13,832 for two); infant free. The exact Aug 30 week and accommodation inventory require a call.",facts:[["Exact 2026","$11,228 lodge"],["Cabin/suite","$13,832"],["Infant","No charge"]],images:["flathead-hero.jpg","flathead-family.jpg"],url:"https://www.flatheadlakelodge.com/",details:"https://www.flatheadlakelodge.com/rates/"},
  {id:"lone",name:"Lone Mountain Ranch",place:"Big Sky · Yellowstone west",coords:[45.276988,-111.324653],price:"$$$$",structure:"Package or room options",meals:"3 meals on Summer Discovery",baby:"Kids program begins at 3",horses:"Riding included in package",luxury:"Historic-cabin polish",fit:"caution",fitText:"Season edge",tags:["inclusive","splurge"],badges:["All-inclusive option","Farm-to-table","Yellowstone tours"],summary:"A refined 25-cabin ranch with the best Big Sky position and a serious dining identity. Summer Discovery can bundle the cabin, meals, ranch activities, horseback riding and Yellowstone touring.",caution:"The Lone Mountain Rangers program is ages 3–14 and runs Memorial Day through Labor Day. Your one-year-old will need parent coverage, and the target dates begin as that program ends.",facts:[["Cabins","1–6 bedrooms"],["BZN drive","~50 minutes"],["2026 price","Request quote"]],images:["lone-hero.jpg","lone-horses.jpg"],url:"https://lonemountainranch.com/",details:"https://lonemountainranch.com/summer-discovery/"},
  {id:"ranch320",name:"320 Guest Ranch",place:"Gallatin Canyon · Yellowstone west",coords:[45.102942,-111.214815],price:"$$",structure:"Flexible cabin nights",meals:"Restaurant / picnic à la carte",baby:"Family-friendly; no care",horses:"Book rides separately",luxury:"Comfortable, not resorty",fit:"good",fitText:"Strong",tags:["flexible"],badges:["Best value","Cabins","45 min to West Yellowstone"],summary:"The practical anchor. Updated log cabins, made-from-scratch food and ranch activities sit between Big Sky and Yellowstone. You pay only for what you use and preserve budget for the spa stop.",caution:"This is not an Austrian-style full-service family hotel. There is no infant club, and restaurant hours vary; book a cabin configuration that makes breakfast and early bedtime easy.",facts:[["Big Sky","20 minutes"],["West Yellowstone","45 minutes"],["2026 price","Live booking"]],images:["320-hero.jpg","320-horses.jpg"],url:"https://320ranch.com/",details:"https://320ranch.com/accommodations/"},
  {id:"sage",name:"Sage Lodge",place:"Paradise Valley · Yellowstone north",coords:[45.355057,-110.727003],price:"$$$",structure:"Flexible lodge nights",meals:"Two restaurants; à la carte",baby:"Families welcome; no infant club",horses:"Ranch setting, not dude ranch",luxury:"Best spa + dining balance",fit:"good",fitText:"Strong",tags:["flexible"],badges:["Spa","Locally sourced dining","35 min to Yellowstone"],summary:"The strongest adult-luxury analogue to Forsthofgut: contemporary mountain design, a Yellowstone River setting, strong food and a real spa. It is a resort headquarters, not a working farm stay.",caution:"The main spa is in renovation in 2026; treatments are operating from a Ranch House while hot tub, sauna and steam-room access may be unavailable. Confirm the current timeline before paying a premium.",facts:[["Private land","1,200 acres"],["Yellowstone","35 minutes"],["2026 price","Live booking"]],images:["sage-hero.jpg","sage-casting.jpg"],url:"https://sagelodge.com/",details:"https://sagelodge.com/about/"},
  {id:"mountain-sky",name:"Mountain Sky Guest Ranch",place:"Paradise Valley · Emigrant",coords:[45.309478,-110.916184],price:"$$$$+",structure:"Sunday–Sunday, 7 nights",meals:"All meals included",baby:"Babysitting available, extra",horses:"Deep ranch program",luxury:"Pool, golf + wellness",fit:"poor",fitText:"Calendar mismatch",tags:["inclusive","splurge"],badges:["All-inclusive","Babysitting under 2","Spa + pool"],summary:"On paper, this is the closest match to the Austria brief: elevated ranch life, all meals, horses, pool, golf, hiking and wellness, plus babysitting for children under two.",caution:"Published 2027 family season ends Aug 22; fall roundup weeks are adults-only. The published 2027 studio floor is $15,350 plus $1,000 for an infant, tax and 9% service. Treat 2026 target dates as unlikely until the ranch confirms.",facts:[["Published floor","$16,350 + fees"],["Stay","7 nights only"],["Kids club","Age 2+"]],images:["sky-hero.jpg","sky-family.jpg"],url:"https://www.mountainsky.com/",details:"https://www.mountainsky.com/packages/family-season/"},
  {id:"rock-creek",name:"The Ranch at Rock Creek",place:"Philipsburg · western Montana",coords:[46.256394,-113.522443],price:"$$$$+",structure:"All-inclusive, quote-only",meals:"3 gourmet meals + drinks",baby:"Crib, high chair, childproofing",horses:"Twice-daily guided activities",luxury:"Highest-touch full service",fit:"good",fitText:"Excellent / $$$",tags:["inclusive","splurge"],badges:["All-inclusive","Baby gear","Babysitting available"],summary:"The no-compromise answer: 6,600 acres, polished cabins and suites, three meals, premium drinks and two guided activity blocks daily. It solves more baby logistics than almost any Montana competitor.",caution:"Kids club starts at 4; babysitting costs extra, and children under 12 need supervision outside club. Rates are by inquiry and are likely to sit far beyond the trip’s working budget.",facts:[["Land","6,600 acres"],["Activities","2 daily"],["Price","Request quote"]],images:["rock-hero.webp","rock-horses.webp"],url:"https://theranchatrockcreek.com/",details:"https://theranchatrockcreek.com/groups/family-reunions/"},
  {id:"paws-up",name:"Paws Up Montana",place:"Greenough · Blackfoot Valley",coords:[46.918594,-113.435501],price:"$$$$+",structure:"2-night fall minimum",meals:"3 meals + beverages included",baby:"Age 3 and under no supplement",horses:"Working cattle-ranch setting",luxury:"Big-resort adventure menu",fit:"good",fitText:"Strong / $$$",tags:["inclusive","splurge"],badges:["Meals included","Baby free","Flexible fall minimum"],summary:"A giant 37,000-acre luxury ranch with houses, glamping, food, spa and an enormous activity menu. It is easier to fit into September than a fixed-week dude ranch, but can dominate the budget fast.",caution:"Kids Adventure Club begins at 3. A published four-night summer package starts at $4,930 per person based on a family of four, while guided activities and spa can add more; request a party-specific September quote.",facts:[["Fall minimum","2 nights"],["Age 0–3","No supplement"],["Scale","37,000 acres"]],images:["paws-hero.webp","paws-horses.webp"],url:"https://www.pawsup.com/",details:"https://www.pawsup.com/rate-policies/"}
];

const stayGrid=document.querySelector("#stay-grid");
const mapList=document.querySelector("#map-list");
const scoreBody=document.querySelector("#score-body");
const photoWall=document.querySelector("#photo-wall");

function card(s){return `<article class="stay-card" data-tags="${s.tags.join(" ")}" id="${s.id}"><div class="stay-photos"><img loading="lazy" src="${A+s.images[0]}" alt="${s.name} property view"><img loading="lazy" src="${A+s.images[1]}" alt="${s.name} ranch experience"></div><div class="stay-body"><div class="stay-topline"><span>${s.place}</span><b>${s.price}</b></div><h3>${s.name}</h3><p class="stay-subtitle">${s.structure}</p><div class="stay-badges">${s.badges.map(x=>`<span>${x}</span>`).join("")}</div><p class="stay-summary">${s.summary}</p><div class="stay-facts">${s.facts.map(f=>`<div><small>${f[0]}</small><strong>${f[1]}</strong></div>`).join("")}</div><div class="stay-caution"><strong>For this trip:</strong> ${s.caution}</div><div class="stay-links"><a href="${s.url}" target="_blank" rel="noreferrer">Official site ↗</a><a href="${s.details}" target="_blank" rel="noreferrer">Rates / details ↗</a><a href="#map-section" data-map-target="${s.id}">Show on map ↑</a></div></div></article>`}
stayGrid.innerHTML=stays.map(card).join("");
mapList.innerHTML=stays.map(s=>`<button class="map-item" data-id="${s.id}"><img src="${A+s.images[0]}" alt=""><span><small>${s.place}</small><strong>${s.name}</strong><small>${s.price} · ${s.fitText}</small></span></button>`).join("");
scoreBody.innerHTML=stays.map(s=>`<tr><td>${s.name}</td><td>${s.structure}<br><strong>${s.price}</strong></td><td>${s.meals}</td><td>${s.baby}</td><td>${s.horses}</td><td>${s.luxury}</td><td class="fit-${s.fit}">${s.fitText}</td></tr>`).join("");
photoWall.innerHTML=stays.flatMap(s=>s.images.map((im,i)=>`<a href="${s.url}" target="_blank" rel="noreferrer"><img loading="lazy" src="${A+im}" alt="${s.name} ${i?"experience":"property"}"><span>${s.name} · ${i?"experience":"setting"}</span></a>`)).join("");

document.querySelectorAll("#filters button").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("#filters button").forEach(b=>b.classList.remove("active"));button.classList.add("active");const filter=button.dataset.filter;document.querySelectorAll(".stay-card").forEach(c=>c.hidden=filter!=="all"&&!c.dataset.tags.split(" ").includes(filter));}));

const map=L.map("map",{scrollWheelZoom:false}).setView([46.45,-112.75],6);
L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);
const markerById={};
stays.forEach(s=>{const marker=L.marker(s.coords).addTo(map).bindPopup(`<div class="popup"><img src="${A+s.images[0]}" alt=""><strong>${s.name}</strong><p>${s.place}<br>${s.price} · ${s.fitText}</p></div>`);markerById[s.id]=marker;});
const routeIds=["clydesdale","ranch320","sage"];
L.polyline(routeIds.map(id=>stays.find(s=>s.id===id).coords),{color:"#c76a3c",weight:4,opacity:.9,dashArray:"10 8"}).addTo(map);
function openStay(id){const s=stays.find(x=>x.id===id);map.flyTo(s.coords,8,{duration:.7});markerById[id].openPopup();document.querySelectorAll(".map-item").forEach(x=>x.classList.toggle("active",x.dataset.id===id));}
document.querySelectorAll(".map-item").forEach(b=>b.addEventListener("click",()=>openStay(b.dataset.id)));
document.querySelectorAll("[data-map-target]").forEach(a=>a.addEventListener("click",()=>setTimeout(()=>openStay(a.dataset.mapTarget),250)));
